{
 "title": "Gitlab / User actions",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   {
    "name": "username",
    "label": "Username",
    "query": "select distinct author_username from events"
   },
   {
    "name": "action",
    "label": "Action",
    "query": "select distinct action_name from events"
   },
   {
    "name": "target",
    "label": "Target",
    "query": "select distinct target_type from events"
   },
   {
    "name": "project",
    "label": "Project",
    "query": "select name_with_namespace from projects"
   },
   {
    "name": "resolution",
    "label": "Resolution",
    "query": "1h,6h,12h,1d,7d,14d,30d,60d,180d,1Y"
   }
  ]
 },
 "panels": [
  {
   "title": "Total",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "All events",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroup(e.created_at, $resolution),\n  count(*)\nFROM events as e\nJOIN projects as p on e.project_id=p.id\nWHERE\n  $__timeFilter(e.created_at)\n  and author_username in ($username)\n  and action_name in ($action)\n  and target_type in ($target)\n  and p.name_with_namespace in ($project)\ngroup by time\nORDER BY 1"
      }
     ]
    },
    {
     "title": "All events by action",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroup(e.created_at, $resolution),\n  action_name,\n  count(*)\nFROM events as e\nJOIN projects as p on e.project_id=p.id\nWHERE\n  $__timeFilter(e.created_at)\n  and author_username in ($username)\n  and action_name in ($action)\n  and target_type in ($target)\n  and p.name_with_namespace in ($project)\ngroup by time, action_name\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "Total by users",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Events by user",
     "type": "graph",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroup(e.created_at, $resolution),\n  author_username,\n  count(*)\nFROM events as e\nJOIN projects as p on e.project_id=p.id\nWHERE\n  $__timeFilter(e.created_at)\n  and author_username in ($username)\n  and action_name in ($action)\n  and target_type in ($target)\n  and p.name_with_namespace in ($project)\ngroup by 1, author_username\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Events by user and action",
     "type": "graph",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroup(e.created_at, $resolution),\n  count(*),\n  CONCAT(author_username, ' {', action_name, '}') as tags\nFROM events as e\nJOIN projects as p on e.project_id=p.id\nWHERE\n  $__timeFilter(e.created_at)\n  and author_username in ($username)\n  and action_name in ($action)\n  and target_type in ($target)\n  and p.name_with_namespace in ($project)\ngroup by 1, author_username, action_name\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "Total per project",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Events by project",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroup(e.created_at, $resolution),\n  count(*),\n  CONCAT(p.name_with_namespace) as tags\nFROM events as e\nJOIN projects as p on e.project_id=p.id\nWHERE\n  $__timeFilter(e.created_at)\n  and author_username in ($username)\n  and action_name in ($action)\n  and target_type in ($target)\n  and p.name_with_namespace in ($project)\ngroup by 1, p.name_with_namespace\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Events by project and action",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroup(e.created_at, $resolution),\n  count(*),\n  CONCAT(p.name_with_namespace, ' {', e.action_name, '}') as tags\nFROM events as e\nJOIN projects as p on e.project_id=p.id\nWHERE\n  $__timeFilter(e.created_at)\n  and author_username in ($username)\n  and action_name in ($action)\n  and target_type in ($target)\n  and p.name_with_namespace in ($project)\ngroup by 1, p.name_with_namespace, action_name\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Events by project and user",
     "type": "graph",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroup(e.created_at, $resolution),\n  count(*),\n  CONCAT(p.name_with_namespace, ' {', e.author_username, '}') as tags\nFROM events as e\nJOIN projects as p on e.project_id=p.id\nWHERE\n  $__timeFilter(e.created_at)\n  and author_username in ($username)\n  and action_name in ($action)\n  and target_type in ($target)\n  and p.name_with_namespace in ($project)\ngroup by 1, p.name_with_namespace, author_username\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "Pushes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pushes by project",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroup(e.created_at, $resolution),\n  count(*),\n  CONCAT(p.name_with_namespace) as tags\nFROM events as e\nJOIN projects as p on e.project_id=p.id\nWHERE\n  $__timeFilter(e.created_at)\n  and author_username in ($username)\n  and p.name_with_namespace in ($project)\n  and action_name in ('pushed new','pushed to')\ngroup by 1, p.name_with_namespace\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Pushes by user",
     "type": "graph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroup(e.created_at, $resolution),\n  count(*),\n  CONCAT(e.author_username) as tags\nFROM events as e\nJOIN projects as p on e.project_id=p.id\nWHERE\n  $__timeFilter(e.created_at)\n  and author_username in ($username)\n  and p.name_with_namespace in ($project)\n  and action_name in ('pushed new','pushed to')\ngroup by 1, author_username\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "Merge requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Merge request events by project",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroup(e.created_at, $resolution),\n  count(*),\n  CONCAT(p.name_with_namespace) as tags\nFROM events as e\nJOIN projects as p on e.project_id=p.id\nWHERE\n  $__timeFilter(e.created_at)\n  and author_username in ($username)\n  and p.name_with_namespace in ($project)\n  and target_type='MergeRequest'\ngroup by 1, p.name_with_namespace\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Merge request events by user",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroup(e.created_at, $resolution),\n  count(*),\n  CONCAT(e.author_username) as tags\nFROM events as e\nJOIN projects as p on e.project_id=p.id\nWHERE\n  $__timeFilter(e.created_at)\n  and author_username in ($username)\n  and p.name_with_namespace in ($project)\n  and target_type='MergeRequest'\ngroup by 1, author_username\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Opened merge requests by user",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroup(e.created_at, $resolution),\n  count(*),\n  CONCAT(e.author_username) as tags\nFROM events as e\nJOIN projects as p on e.project_id=p.id\nWHERE\n  $__timeFilter(e.created_at)\n  and author_username in ($username)\n  and p.name_with_namespace in ($project)\n  and action_name='opened'\n  and target_type='MergeRequest'\ngroup by 1, author_username\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Accepted merge requests by user",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroup(e.created_at, $resolution),\n  count(*),\n  CONCAT(e.author_username) as tags\nFROM events as e\nJOIN projects as p on e.project_id=p.id\nWHERE\n  $__timeFilter(e.created_at)\n  and author_username in ($username)\n  and p.name_with_namespace in ($project)\n  and action_name='accepted'\n  and target_type='MergeRequest'\ngroup by 1, author_username\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "Comments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "All comments by project",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroup(e.created_at, $resolution),\n  count(*),\n  CONCAT(p.name_with_namespace) as tags\nFROM events as e\nJOIN projects as p on e.project_id=p.id\nWHERE\n  $__timeFilter(e.created_at)\n  and author_username in ($username)\n  and p.name_with_namespace in ($project)\n  and action_name='commented on'\ngroup by 1, p.name_with_namespace\nORDER BY 1"
      }
     ]
    },
    {
     "title": "All comments by user",
     "type": "graph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroup(e.created_at, $resolution),\n  count(*),\n  CONCAT(e.author_username) as tags\nFROM events as e\nJOIN projects as p on e.project_id=p.id\nWHERE\n  $__timeFilter(e.created_at)\n  and author_username in ($username)\n  and p.name_with_namespace in ($project)\n  and action_name='commented on'\ngroup by 1, author_username\nORDER BY 1"
      }
     ]
    }
   ]
  },
  { "title": "Code Review", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Review comments by user",
   "type": "graph",
   "description": "Comments in foreign merge requests",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(e.created_at, $resolution),\n  count(*),\n  CONCAT(e.author_username) as tags\nFROM events as e\nJOIN projects as p on e.project_id=p.id\nWHERE\n  $__timeFilter(e.created_at)\n  and author_username in ($username)\n  and p.name_with_namespace in ($project)\n  and is_review_comment=true\ngroup by 1, author_username\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Review comments by project",
   "type": "graph",
   "description": "Comments by users in foreign merge requests",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(e.created_at, $resolution),\n  count(*),\n  CONCAT(p.name_with_namespace) as tags\nFROM events as e\nJOIN projects as p on e.project_id=p.id\nWHERE\n  $__timeFilter(e.created_at)\n  and author_username in ($username)\n  and p.name_with_namespace in ($project)\n  and is_review_comment=true\ngroup by 1, p.name_with_namespace\nORDER BY 1"
    }
   ]
  }
 ]
}